[package]
name = "beshs/tag"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "stravant/goodsignal@0.1.1"
Trove = "sleitnick/trove@1.4.0"
Component = "sleitnick/component@2.4.8"
Promise = "evaera/promise@4.0.0"