[package]
name = "eezby/lodsystem"
version = "0.0.7"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["aftman.toml", "selene.toml", "stylua.toml", "src", "default.project.json", "README.md", ".gitignore", "Packages"]